name: Unit Tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: "npm"
      - name: Install packages
        run: npm ci
      - name: Lunch Unit test
        run: npm test